### ISSUE TITLE
/status is broken

### ISSUE THREAD

**Issue by yarikoptic** [INCF/BrainImagingPipelines#45]
http://bips.incf.org:8080/status
leads to

```
404 Not Found

The path '/status' was not found.

Traceback (most recent call last):
  File "/home/satra/virtualenvs/bipsdev/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/satra/virtualenvs/bipsdev/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/satra/virtualenvs/bipsdev/lib/python2.7/site-packages/cherrypy/_cperror.py", line 386, in __call__
    raise self
NotFound: (404, "The path '/status' was not found.")
```

**Comment by umarbrowser** [comment]
Can you specific the steps you take to produce dis error, i want to take and fix it
